version: "3"
services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ADMIN_PWD}"
    ports:
      - "27018:27017"

  musicbrain:
    build:
      context: .
      dockerfile: Musicbrain.Dockerfile
    volumes:
      - ./musicbrainapp:/app
    ports:
      - 81:80
    links:
      - "db:mongohost"

  # airflow:
  #   image: apache/airflow:2.0.1
  #   ports:
  #     - "8080:8080"